drop table if exists students;
create table if not exists students (
    id integer,
    age integer,
    live_on_campus boolean
);

select * from students;

insert into students values 
(1, 15, true),
(2, 18, false),
(3, 19, true),
(4, 17, true),
(5, 20, false);

-- Give me count of the students who live off the campus 

select count(*)
from students
where live_on_campus = false;

-- Give me count of students who 